CREATE DATABASE IF NOT EXISTS `LIGUES` DEFAULT CHARACTER SET UTF8MB4 COLLATE utf8_general_ci;
USE `LIGUES`;

CREATE TABLE `EMPLOYE` (
  `id` VARCHAR(42),
  `nom` VARCHAR(42),
  `premom` VARCHAR(42),
  `mail` VARCHAR(42),
  `password` VARCHAR(42),
  `datearrive` VARCHAR(42),
  `datedepart` VARCHAR(42),
  `id_1` VARCHAR(42),
  `id_2` VARCHAR(42),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `LIGUE` (
  `id` VARCHAR(42),
  `nom` VARCHAR(42),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE `ROLE` (
  `id` VARCHAR(42),
  `nom` VARCHAR(42),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;

ALTER TABLE `EMPLOYE` ADD FOREIGN KEY (`id_2`) REFERENCES `ROLE` (`id`);
ALTER TABLE `EMPLOYE` ADD FOREIGN KEY (`id_1`) REFERENCES `LIGUE` (`id`);